server:
  port: 8080

spring:
  datasource:
    username: root
    password: bxy0516
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisdemo?serverTimezone=GMT%2B8

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.ayahiro.mybatis.entity

#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  #params: count=countSql
